library(argparse)
library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)


################################
# Process command line arguments
################################
parser <- ArgumentParser(description="Plot expected versus observed relative abundance (mapped basepairs) for each species in a barplot")
parser$add_argument('-i', metavar='--input', type='character', 
                    help="Input file: KMA summary .tsv file, generated by Aggregate_by_OTU.R")
parser$add_argument('-c', metavar='--category', type='character',
                    help="Experiment category to compare, should be an experiment-level variable")
args <- parser$parse_args()

KMA <- read.csv(args$i, sep = "\t")
Compare_category <- args$c


# barplots: To compare organism abundance between a limited amount of experiments
bar_exp_v_obs <- function(df, categorical){
  
  # categorical: variable to compare (e.g. experiments)
  
  # initial filter step + format fill variables
  df <- df %>%
    filter(p_bpTotal > 0) %>%
    filter(!is.na(Perc_gDNA)) %>%
    filter(!is.na({{categorical}})) %>%
    arrange(desc(Perc_gDNA), {{categorical}}) 
  df$OTU_ab <- paste0(df$OTU, " - ", signif(df$Perc_gDNA, digits = 2), "%")
  df$OTU_ab <- ordered(df$OTU_ab, levels=unique(df$OTU_ab))
  
  # create color palette for non-reference levels
  # fillcolors <- brewer.pal(n=length(fill_lvls), "Set1") 
  
  plot <- df %>%
    ggplot(aes(x=OTU_ab, y=100*p_bpTotal/Perc_gDNA, fill={{categorical}})) +
    # here, the position_dodge2 makes sure that bars are of constant width, even when missing data
    geom_col(position=position_dodge2(preserve = "single"), color="black", width = 0.6) + 
    theme_classic() +
    theme(axis.text.x = element_text(angle=-45, hjust=0.0, size=16),
          axis.text.y = element_text(size=16),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size=20),
          legend.position = "top",
          legend.title = element_text(size=20),
          legend.text = element_text(size=16),
          plot.margin = margin(2, 5.5, 2, 2, "cm")) +
    guides(fill = guide_legend(nrow = 2, byrow = TRUE)) +
    coord_cartesian(ylim=c(0,2)) +
    geom_hline(yintercept=1, linetype="dashed") +
    ylab("Ratio observed/expected relative abundance")
  
  return(plot)
}

plot <- bar_exp_v_obs(KMA, !!sym(Compare_category))

pdf(NULL)
exportpath <- str_replace(args$i, "\\w+\\.tsv?", paste0("Barplot_exp_v_obs_", Compare_category, ".png")) 
print(exportpath)
print(plot)
ggsave(exportpath, width = 16, height = 9, dpi = 100)
