library(argparse)
library(data.table)
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)


################################
# Process command line arguments
################################
parser <- ArgumentParser(description="Plot expected versus observed relative abundance (mapped basepairs)")
parser$add_argument('-i', metavar='--input', type='character', 
                    help="Input file: KMA summary .tsv file, generated by Aggregate_by_OTU.R, with reference community data")
parser$add_argument('-c', metavar='--category', type='character', default="Experiment",
                    help="Experiment category to compare, should be an experiment-level variable")
args <- parser$parse_args()

KMA <- read.csv(args$i, sep = "\t")
Compare_category <- args$c



# heatmap clustering different experimental parameters
heatmap_exp_v_obs <- function(df, categorical){
  # df: data, needs to include a Perc_gDNA var, with expected abundances
  # x: Categorical to be compared (e.g. experimental parameter)
  # ref category: organisms in spike-in community and their expected abundances
  
  df <- df %>%
    filter(p_bpTotal > 0) %>%
    mutate(xaxis = {{categorical}}) %>% 
    filter(!is.na(Perc_gDNA)) %>%
    arrange(desc(Perc_gDNA)) %>%
    mutate(norm_abundance=log2(100*p_bpTotal/Perc_gDNA))
  df$OTU_ab <- paste0(df$OTU, " - ", signif(df$Perc_gDNA, digits = 2), "%")
  df$OTU_ab <- ordered(df$OTU_ab, levels=unique(df$OTU_ab))
  
  # make matrix to cluster categorical
  cl <- df %>%
    select(OTU_ab, norm_abundance, xaxis) %>%
    pivot_wider(names_from = xaxis, values_from = norm_abundance, values_fill = 0)
  clmatrix <- as.matrix(cl[2:ncol(cl)])
  rownames(clmatrix) <- cl$OTU_ab
  clmatrix <- t(clmatrix)
  
  # hierarchical clustering of categorical
  ord <- hclust(dist(clmatrix))$order
  ord_exper <- rownames(clmatrix)[ord]
  # order the experiments
  df$xaxis <- ordered(df$xaxis, levels = ord_exper)
  
  heatmap <- df %>%
    ggplot(aes(x=xaxis, y=OTU_ab)) +
    geom_tile(aes(fill=norm_abundance)) +
    scale_fill_gradient2(name="Log2 of ratio observed/expected",
                         low="blue", mid="#e6e6e6", high="red", midpoint = 0) +
    #reverse organism order on heatmap y axis (i.e. top=high abundance, bottom=low)s
    scale_y_discrete(limits=rev, name=NULL) + 
    scale_x_discrete(position = "top", name=NULL) +
    theme_classic() +
    theme(axis.text.x = element_text(angle=-45, hjust=0.9),
          axis.title.x = element_blank(),
          axis.title.y = element_blank())
  return(heatmap)
}

plot <- heatmap_exp_v_obs(KMA, !!sym(Compare_category))

pdf(NULL)
exportpath <- str_replace(args$i, "\\.tsv?", "_heatmap_exp_v_obs.png")
print(exportpath)
print(plot)
ggsave(exportpath, width = 16, height = 9, dpi = 100)

