
library(argparse)
library(data.table)
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)


################################
# Process command line arguments
################################
parser <- ArgumentParser(description="Plot expected versus observed relative abundance (mapped basepairs)")
parser$add_argument('-i', metavar='--input', type='character', 
                    help="Input file: KMA summary .tsv file, generated by Aggregate_by_OTU.R")
parser$add_argument('-c', metavar='--category', type='character', default="Experiment",
                    help="Experiment category to compare, should be an experiment-level variable")
parser$add_argument('-r', metavar='--reference', type='logical', default=FALSE,
                    help="Indicate if reference community should be labeled")
args <- parser$parse_args()

KMA <- read.csv(args$i, sep = "\t")
Compare_category <- args$c
ref_TrueFalse <- args$r



# heatmap clustering different experimental parameters
heatmap_all_org <- function(df, categorical, ref=FALSE){
  # df: data, needs to include a Perc_gDNA var, with expected abundances
  
  # normalise the RA of each species
  df <- df %>%
    filter(mean_queryID > 0) %>%
    filter(p_bpTotal > 0) %>%
    mutate(xaxis = {{categorical}}) %>%
    group_by(xaxis) %>%
    mutate(huetotal = sum(p_bpTotal)) %>%
    mutate(
      norm_abundance= p_bpTotal/huetotal,
      norm_abundance=log10(norm_abundance))
  
  # make matrix to cluster samples (= experiments)
  cl <- df %>%
    select(OTU, norm_abundance, xaxis) %>%
    pivot_wider(names_from = xaxis, values_from = norm_abundance, values_fill = 0)
  clmatrix <- as.matrix(cl[2:ncol(cl)])
  rownames(clmatrix) <- cl$OTU
  clmatrix <- t(clmatrix)
  
  # hierarchical clustering of experiments
  ord <- hclust(dist(clmatrix))$order
  ord_exper <- rownames(clmatrix)[ord]
  # order the experiments
  df$xaxis <- ordered(df$xaxis, levels = ord_exper)
  
  # order Organisms by median occurence for all databases
  org_order <- df %>% group_by(OTU) %>%
    summarize(med = median(norm_abundance, na.rm = TRUE), .groups = "drop") %>%
    arrange(desc(med)) %>% select(OTU) %>% distinct()
  org_order <- as.character(org_order[[1]])
  
  # if reference category is present, correct the order: reference organisms on top
  if(ref){
    ref_com <- df %>% filter(!is.na(Perc_gDNA)) %>% 
      select(OTU, Perc_gDNA) %>% 
      distinct() %>%
      arrange(desc(Perc_gDNA))
    ref_com$p_bpTotal <- ref_com$Perc_gDNA/100
    ref_com[Compare_category] = "Theoretical distribution"
    ref_OTU <- ordered(ref_com$OTU)
    
    org_order_ref <- as.character(ref_OTU)
    
    org_order_other <- df %>% ungroup() %>% filter(is.na(Perc_gDNA)) %>% 
      group_by(OTU) %>%
      summarize(med = median(norm_abundance, na.rm = TRUE), .groups = "drop") %>%
      arrange(desc(med)) %>% select(OTU) %>% distinct()
    org_order_other <- as.character(org_order_other[[1]])
    org_order_other <- org_order_other[!(org_order_other %in% org_order_ref)] # remove ref organisms out of other organisms
    
    org_order <- c(org_order_ref, org_order_other)
  }
  
  df <- df %>% mutate(OTU= ordered(OTU, levels=org_order))
  
  # define midpoint for heatmap color hue
  midpoint <- median(df$norm_abundance, na.rm = TRUE)
  
  heatmap <- df %>%
    ggplot(aes(x=xaxis, y=OTU)) +
    geom_tile(aes(fill=norm_abundance)) +
    scale_fill_gradient2(name="Log10 of relative abundance \n(mapped bp)",
                         low="blue", mid="#e6e6e6", high="red", midpoint = midpoint) +
    #reverse organism order on heatmap y axis (i.e. top=high abundance, bottom=low)s
    scale_y_discrete(limits=rev, name=NULL) + 
    scale_x_discrete(position = "top", name=NULL) +
    theme_classic() +
    theme(axis.text.x = element_text(angle=-45, hjust=0.9, size = 16),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          legend.text = element_text(size = 16),
          legend.title = element_text(size = 16))
  return(heatmap)
}

plot <- heatmap_all_org(KMA, !!sym(Compare_category), ref_TrueFalse)

pdf(NULL)
exportpath <- str_replace(args$i, "\\.tsv?", "_heatmap_all.png")
print(exportpath)
print(plot)
ggsave(exportpath, width = 20, height = 20, dpi = 100)
