library(argparse)
library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)

################################
# Process command line arguments
################################
parser <- ArgumentParser(description="Plot mapped basepairs vs template coverage, optionally label reference community members (if present)")
parser$add_argument('-i', metavar='--input', type='character', 
                    help="Input file: KMA summary .tsv file, generated by Aggregate_by_OTU.R")
parser$add_argument('-r', metavar='--reference', type='logical', default=FALSE,
                    help="Indicate if reference community should be labeled")
args <- parser$parse_args()

KMA <- read.csv(args$i, sep = "\t")
KMA <- KMA %>% filter(!is.na(OTU)) %>%
  filter(!is.na(Experiment))

if(args$r){
  
  KMA$refcomm <- !is.na(KMA$Perc_gDNA)
  KMA$OTU_abb <- paste0(str_sub(KMA$OTU, 1, 1), ".", 
                        str_extract(KMA$OTU, "\\s\\w{2}"))
  KMA$OTU_abb <- ifelse(KMA$refcomm, KMA$OTU_abb, NA)
  
  for (i in unique(KMA$Experiment)){
    print(paste("making plot: ", i))
    plot <- KMA %>% 
      filter(Experiment==i) %>% 
      ggplot(aes(x = p_bpTotal, y=mean_template_coverage, col=refcomm)) +
      geom_point() +
      geom_text(aes(label=OTU_abb), hjust=-0.1) +
      scale_x_log10(limits=c(1e-07, NA)) +
      theme_bw() +
      ggtitle(i) +
      guides(color = guide_legend(title = "Part of spike-in community"))
    
    pdf(NULL)
    exportpath <- str_replace(args$i, "\\w+\\.tsv?", paste0(i,"_bps_v_cov.png"))
    print(plot)
    ggsave(exportpath, width = 16, height = 9, dpi = 100)
    
  }
  
} else{
  print("no reference added")
  for (i in unique(KMA$Experiment)){
    print(paste("making plot: ", i))
    plot <- KMA %>% 
      filter(Experiment==i) %>% 
      ggplot(aes(x = p_bpTotal, y=mean_template_coverage)) +
      geom_point() +
      scale_x_log10(limits=c(1e-07, NA)) +
      theme_bw() +
      ggtitle(i)
    
    pdf(NULL)
    exportpath <- str_replace(args$i, "\\w+\\.tsv?", paste0(i,"_bps_v_cov.png")) 
    print(exportpath)
    print(plot)
    ggsave(exportpath, width = 16, height = 9, dpi = 100)
    
  }
  
}