library(dplyr)
library(stringr)
library(ggplot2)
library(data.table)

################################
# Process command line arguments
################################
main <- function(){
  args <- commandArgs(trailingOnly = TRUE)
  #default settings
  reference <- ""
  taxlevel <- "species"
  
  for (i in 1:length(args)){
    
    if (args[i] == "-i"){
      if (!str_detect(args[[i+1]], "\\.tsv")){
        usage()
      }
      filename <- args[[i+1]]
    }
    else if (args[i] == "-t"){
      if (!(args[[i+1]] %in% c("species", "genus"))){
        usage()
      }
      if (args[[i+1]]=="genus"){
        taxlevel <- "genus"
      }else {
        taxlevel <- "species"
      }
      
    }else if (args[i] == "-r"){
      if (!str_detect(args[[i+1]], "\\.csv")){
        usage()
      }
      reference <- args[[i+1]]
    }
    
  }
  argslist <- list(file=filename, taxlevel=taxlevel, ref=reference)
  return(argslist)
  
}

usage <- function() {
  cat(
    "usage: Rscript AlignmentXcomp_dotplot.R -i input.tsv -s statistic -t taxonomic_level",
    "  -i: Input tsv file comparing alignment to ResFdb with alignment to taxonomy db (Generated by Comparison_alignments.py)", 
    "  -r: Filepath to a reference ;-separated csv, containing 2 columns: Organism;ARG, default: None",
    "  -t: taxonomic level at which to compare alignments. One of [species, genus]. Default: species",sep = "\n")
}

args <- main()
filename <- args$file
taxlevel_species <- args$taxlevel=="species"
taxlevel_genus <- args$taxlevel=="genus"
reference <- args$ref


###################################
# read Reference community AMR data
###################################

if(reference!=""){
  reference_data <- read.csv(reference, sep = "\t") %>%
    mutate(Reference_AMR_link=TRUE)
  reference_ARGs <- data.frame(reference_data$ARG) %>% mutate(Reference_AMR=TRUE)
}


##########################################
# functions to clean ARG and organism name
##########################################

clean_org_name <- function(organism){
  organism <- str_remove_all(organism, "Synthetic|\\[|\\]|\\scf.")
  organism <- str_replace_all(organism, "_", " ")
  organism <- str_replace_all(organism, "E.coli.*", "Escherichia coli")
  organism <- str_replace_all(organism, "veillonella", "Veillonella")
  organism <- str_replace_all(organism, "\\.", " ")
  organism <- str_extract(organism, "[:upper:]{1}[:lower:]+\\s[:alpha:]+\\.?")
  organism <- str_replace(organism, "Clostridium difficil+e", "Clostridioides difficile")
  return(organism)
}

clean_ARG_names <- function(amr_gene){
  amr_gene <- str_remove(amr_gene, "(_|-).+")
  return(amr_gene)
}


####################################
# read in alignment comparison file
####################################

data <- fread(filename, sep = "\t", integer64 = "numeric")

data <- mutate(data, 
               Template1=clean_org_name(Template1),
               Organism=Template1,
               Genus=str_extract(Organism, "[:upper:]{1}[:lower:]+"),
               Template2=clean_ARG_names(Template2),
               ARG=Template2)

if(taxlevel_species){
  
  data <- data %>%
    group_by(Organism, ARG) %>%
    summarize(n_reads=sum(n_reads, na.rm = TRUE),
              sum_readlength=sum(sum_readlength, na.rm = TRUE),
              n_match_bases1=sum(n_match_bases1, na.rm = TRUE),
              n_match_bases2=sum(n_match_bases2, na.rm = TRUE),
              Template1_length=sum(Template1_length)/n(),
              Template2_length=sum(Template2_length)/n()) %>%
    mutate(Coverage_ARG = n_match_bases2)
  
  if(reference==""){
    plot <- data %>%
      ggplot(aes(x=ARG, y=Organism)) +
      geom_point(aes(size=n_reads)) +
      theme_classic() +
      guides(color = guide_legend(override.aes = list(size = 8)))
  }else{
    data <- merge(data, reference_data, by=c("Organism", "ARG"), all=TRUE) %>%
      mutate(Reference_AMR_link=ifelse(Reference_AMR_link, Reference_AMR_link, FALSE),
             Reference_AMR_link=ifelse(is.na(Reference_AMR_link), FALSE, Reference_AMR_link)) 
    
    plot <- data %>%
      ggplot(aes(x=ARG, y=Organism)) +
      geom_point(aes(col=Reference_AMR_link, size=n_reads)) +
      theme_classic() +
      guides(color = guide_legend(override.aes = list(size = 8)))
  }
  
} else if(taxlevel_genus){
  
  data <- data %>% 
    group_by(Genus, ARG) %>%
    summarize(n_reads=sum(n_reads, na.rm = TRUE),
              sum_readlength=sum(sum_readlength, na.rm = TRUE),
              n_match_bases1=sum(n_match_bases1, na.rm = TRUE),
              n_match_bases2=sum(n_match_bases2, na.rm = TRUE),
              Template1_length=sum(Template1_length)/n(),
              Template2_length=sum(Template2_length)/n()) %>%
    mutate(Coverage_ARG = n_match_bases2)
  
  if(reference==""){
    plot <- data %>%
      ggplot(aes(x=ARG, y=Genus)) +
      geom_point(aes(size=n_reads)) +
      theme_classic() +
      guides(color = guide_legend(override.aes = list(size = 8)))
  }else{
    reference_data <- mutate(reference_data, Genus=str_extract(Organism, "[:upper:]{1}[:lower:]+"))
    
    data <- merge(data, reference_data, by=c("Genus", "ARG"), all=TRUE) %>%
      mutate(Reference_AMR_link=ifelse(Reference_AMR_link, Reference_AMR_link, FALSE),
             Reference_AMR_link=ifelse(is.na(Reference_AMR_link), FALSE, Reference_AMR_link)) 
    
    plot <- data %>%
      ggplot(aes(x=ARG, y=Genus)) +
      geom_point(aes(col=Reference_AMR_link, size=n_reads)) +
      theme_classic() +
      guides(color = guide_legend(override.aes = list(size = 8)))
  }
}

pdf(NULL)
exportpath <- str_replace(filename, "\\.tsv?", "_AMRlinks.png")
print(exportpath)
print(plot)
ggsave(exportpath, width = 16, height = 9, dpi = 100)