library(argparse)
library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)


################################
# Process command line arguments
################################
parser <- ArgumentParser(description="Plot read length statistics per (reference community) species")
parser$add_argument('-i', metavar='--input', type='character', nargs='+',
                    help="Input file: readstats.tsv file, generated by Readlevel_align_stats.py")
parser$add_argument('-r', metavar='--reference', type='character', default="",
                    help="Indicate filepath to reference community")
args <- parser$parse_args()

readstats <- args$i
stopifnot(args$r != "")
ref_com <- read.csv(args$r, sep=";", dec=",")

# Parse list of readstat files, extract experiment name from filename, add to each readstat dataset
exp_names <- lapply(readstats, str_extract, "\\w+_readstats.tsv$")
exp_names <- lapply(exp_names, str_remove, "_readstats.tsv")
readstats <- lapply(readstats, read.csv, sep="\t")
for (k in 1:length(readstats)){
  readstats[[k]]$Experiment <- exp_names[[k]]
}
readstats <- rbindlist(readstats)

# Parse reference community data
ref_com$OTU <- ref_com$Organism
ref_com <- ref_com %>% select(OTU, Perc_gDNA) %>% 
  distinct() %>%
  arrange(desc(Perc_gDNA))
ref_OTU <- ordered(ref_com$OTU)

# Function to clean organism names (to species level)
clean_org_name <- function(organism){
  organism <- str_remove_all(organism, "Synthetic|\\[|\\]|\\scf.")
  organism <- str_replace_all(organism, "_", " ")
  organism <- str_replace_all(organism, "E.coli.*", "Escherichia coli")
  organism <- str_replace_all(organism, "veillonella", "Veillonella")
  organism <- str_replace_all(organism, "\\.", " ")
  organism <- str_extract(organism, "[:upper:]{1}[:lower:]+\\s[:alpha:]+\\.?")
  organism <- str_replace(organism, "Clostridium difficil+e", "Clostridioides difficile")
  return(organism)
}

plot <- readstats %>%
  mutate(OTU = clean_org_name(Template)) %>%
  filter(OTU %in% ref_com$OTU) %>%
  mutate(OTU = ordered(OTU, levels=ref_OTU)) %>%
  group_by(OTU, Experiment) %>%
  summarize(mean_readlength = mean(Length)) %>%
  ggplot(aes(x=OTU, y=mean_readlength, fill=Experiment)) +
  geom_col(position = "dodge", color="black") +
  coord_cartesian(ylim=c(0,15000)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90))

pdf(NULL)
exportpath <- paste0(getwd(), "/Mean_readlengths_by_species.png")  # !!! always same filename; will overwrite previous ones
print(exportpath)
print(plot)
ggsave(exportpath, width = 16, height = 9, dpi = 100)