library(argparse)
library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)


################################
# Process command line arguments
################################
parser <- ArgumentParser(description="Plot expected versus observed relative abundance (mapped basepairs)")
parser$add_argument('-i', metavar='--input', type='character', 
                    help="Input file: KMA summary .tsv file, generated by Aggregate_by_OTU.R")
parser$add_argument('-c', metavar='--category', type='character',
                    help="Experiment category to compare, should be an experiment-level variable")
args <- parser$parse_args()

KMA <- read.csv(args$i, sep = "\t")
Compare_category <- args$c

scatter_exp_v_obs <- function(df, categorical){
  plotdata <- df %>% 
    filter(!is.na({{categorical}})) %>%
    filter(!is.na(p_bpTotal))
  plot <- 
    ggplot() + 
    geom_point(data = plotdata, 
               aes(x=Perc_gDNA/100, y=p_bpTotal, color={{categorical}}), 
               position = position_dodge2(width = 0.2), size=2.5) +
    geom_abline(aes(slope=1, intercept=0), linetype=2) +
    scale_color_brewer(palette="Set1") +
    theme_classic() +
    theme(axis.text.x = element_text(size = 16),
          axis.text.y = element_text(size = 16),
          axis.title.x = element_text(size = 16),
          axis.title.y = element_text(angle=90, size = 16),
          legend.text = element_text(size=16),
          legend.title = element_text(size=20))
  plot <- plot + 
    scale_y_continuous(name="Observed distribution",
                       trans='log10', labels = scales::percent) +
    scale_x_continuous(name="Theoretical distribution",
                       trans='log10', labels = scales::percent) +
    guides(color = guide_legend(override.aes = list(size = 8)))
  
  return(plot)
}


plot <- scatter_exp_v_obs(KMA, !!sym(Compare_category))

pdf(NULL)
exportpath <- str_replace(args$i, "\\w+\\.tsv?", paste0("Exp_v_obs_", Compare_category, ".png")) 
print(exportpath)
print(plot)
ggsave(exportpath, width = 16, height = 9, dpi = 100)